server:
  port: 8082


spring:
  application:
    name: participant-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/participant_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:quyetbh}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

player:
    service:
        url: http://localhost:8080

session:
    service:
        url: http://localhost:8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8088/eureka/