server:
  port: 8080


spring:
  application:
        name: player-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/player_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:quyetbh}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8088/eureka/